import type { Metadata } from "next";
import { Geist, Geist_Mono, Albert_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import Navbar4 from "@/components/shared/navbar/Navbar4";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import ProvidersContainer from "@/providersContainer/ProvidersContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const albert_Sans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecomus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${albert_Sans.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* <Navbar
          categories={[
            { title: "music" },
            { title: "food" },
            { title: "fashion" },
          ]}
        /> */}
        {/* <Navbar2 /> */}
        {/* <Navbar3 /> */}
        <ProvidersContainer>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar4 />
            {children}
            <Footer />
            <Toaster
              position="top-right"
              richColors
              expand={true}
              closeButton
            />
          </ThemeProvider>
        </ProvidersContainer>
      </body>
    </html>
  );
}
